language: python
python: "2.7.14"
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install cookiecutter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget "http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
install:
  - cookiecutter https://github.com/kitconcept/cookiecutter-plone.git --no-input
script:
  - (cd project-name && make build)
  - (cd project-name && make test)
